# Generated by Django 5.1.3 on 2025-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(default="default_username", max_length=20),
            preserve_default=False,
        ),
    ]
